import {test,expect} from "@playwright/test";
test("database facets combine, save and rename without scraping",async({page})=>{
 let searches:any[]=[];let last="";
 await page.route("**/api/backend/application-assistant/browse-searches**",async route=>{const req=route.request();if(req.method()==="POST")searches=[{id:"test",...req.postDataJSON()}];if(req.method()==="PUT")searches=[{id:"test",...req.postDataJSON()}];if(req.method()==="DELETE")searches=[];await route.fulfill({json:{searches}});});
 await page.route("**/api/backend/jobs/discover**",async route=>{const url=new URL(route.request().url());if(url.pathname.endsWith("filter-options"))return route.fulfill({json:{titles:["Product Manager","Business Intelligence Engineer"],companies:["Acme"],specialties:[{value:"pm",label:"Product Manager"},{value:"bie",label:"Business Intelligence / BIE"}],seniorities:["senior"],workModes:["remote"],experience:["3-5"],freshness:["24"],sponsorship:[]}});if(url.pathname.endsWith("/locations"))return route.fulfill({json:{locations:[{value:"Seattle",label:"Seattle",count:1}]}});if(url.pathname.endsWith("/jobs/discover")){last=url.search;return route.fulfill({json:{jobs:[],total:0,page:1,totalPages:0,indexedTotal:0}});}return route.fulfill({json:{running:false}});});
 await page.goto("/jobs/discover");
 await page.getByRole("group",{name:"Job specialty",exact:true}).getByRole("checkbox",{name:"Product Manager",exact:true}).check();
 await page.getByRole("checkbox",{name:"Business Intelligence / BIE",exact:true}).check();
 await page.getByRole("group",{name:"Seniority",exact:true}).getByRole("checkbox",{name:"Senior",exact:true}).check();
 await expect.poll(()=>new URLSearchParams(last).get("specialties")).toBe("pm,bie");
 await expect.poll(()=>new URLSearchParams(last).get("seniorities")).toBe("senior");
 await expect(page.getByRole("checkbox",{name:"On-site",exact:true})).toHaveCount(0);
 await page.getByText("Saved searches · 0",{exact:true}).click();await page.getByRole("textbox",{name:"Saved search name"}).fill("Product and BI");await page.getByRole("button",{name:"Save current filters"}).click();
 await page.getByRole("button",{name:"Rename saved search Product and BI"}).click();await page.getByRole("textbox",{name:"New search name"}).fill("My roles");await page.getByRole("button",{name:"Update name"}).click();await expect(page.getByRole("button",{name:"My roles",exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await page.getByRole("button",{name:/Filters ·/}).click();await expect(page.getByRole("heading",{name:"Find your fit"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.getByRole("button",{name:"Close filters"}).click();
});
test("telemetry charts switch periods and preserve missing timing",async({page})=>{
 let period="";
 await page.route("**/api/backend/diagnostic/**",async route=>{const url=new URL(route.request().url());if(url.pathname.endsWith("/series")){period=url.searchParams.get("period")!;return route.fulfill({json:{period,bucketSeconds:300,updatedAt:"2026-09-12T12:00:00Z",basis:"Current status by last update",buckets:[{timestamp:"2026-09-12T11:00:00Z",submitted:3,failed:1,review:2,skipped:0,other:0,durationSec:60,samples:2},{timestamp:"2026-09-12T11:05:00Z",submitted:0,failed:0,review:0,skipped:0,other:0,durationSec:null,samples:0}]}});}if(url.pathname.endsWith("/health"))return route.fulfill({json:{services:[],overallStatus:"Healthy",updatedAt:"2026-09-12T12:00:00Z"}});if(url.pathname.endsWith("/metrics"))return route.fulfill({json:{period:url.searchParams.get("period"),jobsDiscovered:0,jobsPrepared:0,applicationsAttempted:0,successfulSubmissions:0,submissionSuccessPct:0,stagedForReview:0,failures:0,skipped:0,avgApplicationDurationSec:null,avgResumeTailoringDurationSec:null,modelFallbackCount:0}});return route.fulfill({json:{runs:[],activeRunId:null,errors:[],alarms:[]}});});
 await page.goto("/diagnostic");await expect(page.getByRole("heading",{name:"Activity over time"})).toBeVisible();await expect(page.getByRole("heading",{name:"6 jobs updated"})).toBeVisible();await page.getByRole("radio",{name:"1h",exact:true}).click();await expect.poll(()=>period).toBe("1h");await page.getByRole("button",{name:/3 Submitted/}).focus();await expect(page.getByText(/Submitted 3 · Failed 1/)).toBeVisible();await page.getByText("Inspect chart data & definitions").click();await expect(page.getByRole("cell",{name:"Not recorded",exact:true})).toBeVisible();await page.screenshot({path:"test-results/telemetry-dashboard.png",fullPage:true});await page.setViewportSize({width:390,height:844});await page.emulateMedia({reducedMotion:"reduce"});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
