export type FeatureStatus = "planned" | "in-progress" | "done";
export type FeaturePriority = "P0" | "P1" | "P2" | "P3";

export interface RoadmapFeature {
  id: string;
  title: string;
  description: string;
  status: FeatureStatus;
  priority: FeaturePriority;
  module: string;
  phase: number;
  dependencies: string[];
  technicalNotes: string;
}

export const ROADMAP_MODULES = [
  "Profile OS",
  "Resume Intelligence",
  "Cover Letter Intelligence",
  "Job Discovery",
  "Application Intelligence / ApplyPilot",
  "Recruiter CRM",
  "Networking",
  "Interview OS",
  "Career AI Coach",
  "Learning OS",
  "Career Analytics",
  "Portfolio Builder",
  "Salary Intelligence",
  "Career Knowledge Graph",
  "Automation Engine",
  "Browser Extension",
  "Integrations",
  "Privacy & Data Ownership",
] as const;

export const ROADMAP_PHASES = [
  {
    id: 1,
    name: "ApplyPilot MVP",
    items: [
      "User profile",
      "Resume storage",
      "Job extraction",
      "Autofill detection",
      "Autofill execution",
      "Unknown-field learning",
      "Save application",
      "Basic dashboard",
    ],
  },
  {
    id: 2,
    name: "Application Intelligence",
    items: [
      "Application tracker",
      "Resume-to-job matching",
      "Cover letter generation",
      "Custom question answering",
      "Application analytics",
    ],
  },
  {
    id: 3,
    name: "Recruiter + Interview",
    items: [
      "Recruiter CRM",
      "Follow-up reminders",
      "Interview prep",
      "Mock interview scaffolding",
      "Behavioral story bank",
    ],
  },
  {
    id: 4,
    name: "Career Intelligence",
    items: [
      "Career analytics",
      "Skill gap analysis",
      "Job market insights",
      "Salary intelligence",
      "AI career coach",
    ],
  },
  {
    id: 5,
    name: "Full CareerOS",
    items: [
      "Networking graph",
      "Portfolio builder",
      "Knowledge graph",
      "Automation engine",
      "Integrations",
      "Privacy controls",
    ],
  },
] as const;

export const ROADMAP_FEATURES: RoadmapFeature[] = [
  {
    id: "applypilot-autofill",
    title: "ApplyPilot autofill engine",
    description: "Detect ATS fields, map profile data, attach resume, and learn unknown mappings.",
    status: "in-progress",
    priority: "P0",
    module: "Application Intelligence / ApplyPilot",
    phase: 1,
    dependencies: ["profile-core", "resume-storage"],
    technicalNotes: "Migrated from Arsenal jobfill-extension content scripts and field classifier.",
  },
  {
    id: "profile-core",
    title: "User profile & preferences",
    description: "Canonical profile for name, contact, work auth, and screening defaults.",
    status: "in-progress",
    priority: "P0",
    module: "Profile OS",
    phase: 1,
    dependencies: [],
    technicalNotes: "Shared via career-core schemas; synced between extension and API.",
  },
  {
    id: "resume-storage",
    title: "Resume storage & parsing",
    description: "Upload resume, parse PDF text, hydrate profile and work experience.",
    status: "in-progress",
    priority: "P0",
    module: "Resume Intelligence",
    phase: 1,
    dependencies: ["profile-core"],
    technicalNotes: "Resume parser ported to FastAPI; extension attaches files on ATS forms.",
  },
  {
    id: "job-extraction",
    title: "Job page extraction",
    description: "Extract title, company, location, description, and application URL from job pages.",
    status: "in-progress",
    priority: "P0",
    module: "Job Discovery",
    phase: 1,
    dependencies: [],
    technicalNotes: "Content script heuristics + POST /jobs/extract API scaffold.",
  },
  {
    id: "save-application",
    title: "Save application workflow",
    description: "Track saved jobs and application status from extension popup and dashboard.",
    status: "in-progress",
    priority: "P0",
    module: "Application Intelligence / ApplyPilot",
    phase: 1,
    dependencies: ["job-extraction", "profile-core"],
    technicalNotes: "IndexedDB in extension + REST sync to API.",
  },
  {
    id: "basic-dashboard",
    title: "CareerOS dashboard shell",
    description: "Navigation, module pages, and roadmap command center.",
    status: "in-progress",
    priority: "P0",
    module: "Browser Extension",
    phase: 1,
    dependencies: [],
    technicalNotes: "Next.js app with premium calm UI and roadmap cards.",
  },
  {
    id: "unknown-field-learning",
    title: "Unknown field learning",
    description: "Prompt user for unknown fields and persist mappings for reuse.",
    status: "in-progress",
    priority: "P0",
    module: "Application Intelligence / ApplyPilot",
    phase: 1,
    dependencies: ["applypilot-autofill"],
    technicalNotes: "Learning engine migrated from extension; maps stored via /autofill/map-field.",
  },
  {
    id: "application-tracker",
    title: "Application tracker",
    description: "Pipeline board, statuses, and application detail views.",
    status: "planned",
    priority: "P1",
    module: "Application Intelligence / ApplyPilot",
    phase: 2,
    dependencies: ["save-application"],
    technicalNotes: "Extension dashboard components + web /applications page.",
  },
  {
    id: "cover-letter-gen",
    title: "Cover letter generation",
    description: "Generate tailored cover letters from job + profile context.",
    status: "planned",
    priority: "P1",
    module: "Cover Letter Intelligence",
    phase: 2,
    dependencies: ["profile-core", "job-extraction"],
    technicalNotes: "POST /cover-letter/generate uses OpenRouter via Arsenal LLM client when configured.",
  },
  {
    id: "custom-questions",
    title: "Custom question answering",
    description: "Answer ATS screening questions from learned answers and LLM fallback.",
    status: "planned",
    priority: "P1",
    module: "Application Intelligence / ApplyPilot",
    phase: 2,
    dependencies: ["unknown-field-learning"],
    technicalNotes: "POST /questions/answer scaffold; screening answer bank in profile.",
  },
  {
    id: "recruiter-crm",
    title: "Recruiter CRM",
    description: "Track recruiters, threads, and follow-ups.",
    status: "planned",
    priority: "P2",
    module: "Recruiter CRM",
    phase: 3,
    dependencies: ["application-tracker"],
    technicalNotes: "Email scripts from Arsenal scripts/email to migrate later.",
  },
  {
    id: "interview-prep",
    title: "Interview prep OS",
    description: "Mock interviews, story bank, and prep checklists.",
    status: "planned",
    priority: "P2",
    module: "Interview OS",
    phase: 3,
    dependencies: ["application-tracker"],
    technicalNotes: "Scaffold pages at /interviews.",
  },
  {
    id: "career-analytics",
    title: "Career analytics",
    description: "Funnel metrics, response rates, and activity timelines.",
    status: "planned",
    priority: "P2",
    module: "Career Analytics",
    phase: 4,
    dependencies: ["application-tracker"],
    technicalNotes: "POST /analytics/event ingests extension and web events.",
  },
  {
    id: "salary-intelligence",
    title: "Salary intelligence",
    description: "Comp benchmarks and negotiation insights.",
    status: "planned",
    priority: "P3",
    module: "Salary Intelligence",
    phase: 4,
    dependencies: ["job-extraction"],
    technicalNotes: "Future integration with market data providers.",
  },
  {
    id: "networking-graph",
    title: "Networking graph",
    description: "Relationships, referrals, and warm intro paths.",
    status: "planned",
    priority: "P3",
    module: "Networking",
    phase: 5,
    dependencies: ["recruiter-crm"],
    technicalNotes: "Graph store TBD; page scaffold at /networking.",
  },
  {
    id: "portfolio-builder",
    title: "Portfolio builder",
    description: "Projects, case studies, and public profile site export.",
    status: "planned",
    priority: "P3",
    module: "Portfolio Builder",
    phase: 5,
    dependencies: ["profile-core"],
    technicalNotes: "Uses Project schema from career-core.",
  },
  {
    id: "knowledge-graph",
    title: "Career knowledge graph",
    description: "Connect skills, roles, companies, and outcomes.",
    status: "planned",
    priority: "P3",
    module: "Career Knowledge Graph",
    phase: 5,
    dependencies: ["career-analytics"],
    technicalNotes: "Long-term semantic layer over career events.",
  },
  {
    id: "automation-engine",
    title: "Automation engine",
    description: "Workflow triggers across modules (apply, follow-up, prep).",
    status: "planned",
    priority: "P3",
    module: "Automation Engine",
    phase: 5,
    dependencies: ["application-tracker", "recruiter-crm"],
    technicalNotes: "Leverage Arsenal scheduler when workflows mature.",
  },
  {
    id: "integrations",
    title: "Integrations hub",
    description: "LinkedIn, Gmail, calendar, and ATS connectors.",
    status: "planned",
    priority: "P3",
    module: "Integrations",
    phase: 5,
    dependencies: [],
    technicalNotes: "OAuth and webhook architecture TBD.",
  },
  {
    id: "privacy-controls",
    title: "Privacy & data ownership",
    description: "Export, delete, encryption, and local-first controls.",
    status: "planned",
    priority: "P2",
    module: "Privacy & Data Ownership",
    phase: 5,
    dependencies: [],
    technicalNotes: "User-owned data policy; no hardcoded secrets.",
  },
  {
    id: "ai-coach",
    title: "Career AI coach",
    description: "Guidance across search, apply, interview, and negotiation.",
    status: "planned",
    priority: "P2",
    module: "Career AI Coach",
    phase: 4,
    dependencies: ["career-analytics"],
    technicalNotes: "Uses Arsenal OpenRouter client patterns.",
  },
  {
    id: "learning-os",
    title: "Learning OS",
    description: "Skill development plans tied to target roles.",
    status: "planned",
    priority: "P3",
    module: "Learning OS",
    phase: 4,
    dependencies: ["career-analytics"],
    technicalNotes: "Skill gap analysis drives learning paths.",
  },
];

export function featuresByModule(module: string): RoadmapFeature[] {
  return ROADMAP_FEATURES.filter((f) => f.module === module);
}

export function featuresByPhase(phase: number): RoadmapFeature[] {
  return ROADMAP_FEATURES.filter((f) => f.phase === phase);
}
