"use client";
import {useEffect,useState,type ReactNode} from "react";
import {ChoiceGroup,type Choice} from "@/components/ui/choice-group";
import {SidePanelPortal} from "@/components/side-panel-portal";
import styles from "./browse-filter-controls.module.css";

export type BrowseSelection = {q:string;location:string;company:string;specialties:string[];seniorities:string[];workModes:string[];experience:string;companies:string[];freshness:string;sponsorship:string;sort:string};
export type BrowseOptions = {titles:string[];companies:string[];specialties:Choice[];seniorities:string[];workModes:string[];experience:string[];freshness?:string[];sponsorship?:string[]};
export const EMPTY_BROWSE:BrowseSelection={q:"",location:"",company:"",specialties:[],seniorities:[],workModes:[],experience:"",companies:[],freshness:"all",sponsorship:"all",sort:"relevancy"};
const choices=(pairs:string[][]):Choice[]=>pairs.map(([value,label])=>({value,label}));
const LEVELS=choices([["entry","Entry / Junior"],["mid","Mid-level"],["senior","Senior"],["staff","Staff"],["principal","Principal"],["lead","Lead / Management"],["unspecified","Not stated"]]);
const MODES=choices([["remote","Remote"],["hybrid","Hybrid"],["onsite","On-site"],["unspecified","Not stated"]]);
const DATES=choices([["all","Any time"],["24","24 hours"],["168","7 days"],["720","30 days"]]);
type Saved={id:string;name:string;filters:BrowseSelection};

export function BrowseFilterControls({value,options,onChange,onClear,onFetch,scraping,total,titleInput,locationInput}: {value:BrowseSelection;options:BrowseOptions;onChange:(patch:Partial<BrowseSelection>)=>void;onClear:()=>void;onFetch:()=>void;scraping:boolean;total:number;titleInput:ReactNode;locationInput:ReactNode}) {
  const [open,setOpen]=useState(false);const [mobile,setMobile]=useState(false);const [companyQuery,setCompanyQuery]=useState("");
  const [editing,setEditing]=useState<string|null>(null);const [renameValue,setRenameValue]=useState("");
  const [saved,setSaved]=useState<Saved[]>([]);const [name,setName]=useState("");const [error,setError]=useState("");const [saving,setSaving]=useState(false);
  useEffect(()=>{const media=matchMedia("(max-width:760px)");const update=()=>setMobile(media.matches);update();media.addEventListener("change",update);return()=>media.removeEventListener("change",update);},[]);
  useEffect(()=>{fetch("/api/backend/application-assistant/browse-searches").then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(body=>setSaved(body.searches||[])).catch(()=>setError("Saved searches are unavailable."));},[]);
  const save=async()=>{setSaving(true);setError("");try{const res=await fetch("/api/backend/application-assistant/browse-searches",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,filters:value})});if(!res.ok)throw new Error();setSaved((await res.json()).searches);setName("");}catch{setError("Could not save this search. Try again.");}finally{setSaving(false);}};
  const remove=async(id:string)=>{setError("");try{const res=await fetch(`/api/backend/application-assistant/browse-searches/${id}`,{method:"DELETE"});if(!res.ok)throw new Error();setSaved((await res.json()).searches);}catch{setError("Could not remove this saved search.");}};
  const rename=async(item:Saved)=>{setError("");try{const res=await fetch(`/api/backend/application-assistant/browse-searches/${item.id}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...item,name:renameValue})});if(!res.ok)throw new Error();setSaved((await res.json()).searches);setEditing(null);}catch{setError("Could not rename this saved search.");}};
  const chips:{label:string;remove:()=>void}[]=[];
  for(const key of ["specialties","seniorities","workModes","companies"] as const)for(const item of value[key]){const label=[...options.specialties,...LEVELS,...MODES].find(o=>o.value===item)?.label||item;chips.push({label,remove:()=>onChange({[key]:value[key].filter(v=>v!==item)})});}
  for(const [key,label] of [["q",value.q],["location",value.location],["company",value.company],["experience",value.experience ? `${value.experience} years required` : ""],["freshness",value.freshness!=="all" ? DATES.find(d=>d.value===value.freshness)?.label||`Last ${value.freshness} hours` : ""],["sponsorship",value.sponsorship!=="all" ? `Sponsorship: ${value.sponsorship}` : ""]] as const)if(label)chips.push({label,remove:()=>onChange({[key]:key==="freshness"||key==="sponsorship" ? "all" : ""})});
  const controls=<div className={styles.controls}>
    <div className={styles.searchRow}><label>Job title or keyword{titleInput}</label><label>Locations{locationInput}</label></div>
    <ChoiceGroup label="Job specialty" options={options.specialties} multiple value={value.specialties} onChange={specialties=>onChange({specialties})}/>
    <ChoiceGroup label="Seniority" options={LEVELS.filter(o=>options.seniorities.includes(o.value)||value.seniorities.includes(o.value))} multiple value={value.seniorities} onChange={seniorities=>onChange({seniorities})}/>
    <ChoiceGroup label="Work arrangement" options={MODES.filter(o=>options.workModes.includes(o.value)||value.workModes.includes(o.value))} multiple value={value.workModes} onChange={workModes=>onChange({workModes})}/>
    <ChoiceGroup label="Posted within" options={DATES.filter(o=>o.value==="all"||options.freshness?.includes(o.value)||o.value===value.freshness)} value={[value.freshness]} onChange={([freshness])=>onChange({freshness})}/>
    <details className={styles.more}><summary>More filters · experience, company & sponsorship</summary><div>
      <ChoiceGroup label="Minimum experience requested" options={choices([["","Any"],["0-2","0–2 years"],["3-5","3–5 years"],["6-9","6–9 years"],["10+","10+ years"],["unspecified","Not stated"]]).filter(o=>!o.value||options.experience.includes(o.value)||o.value===value.experience)} value={[value.experience]} onChange={([experience])=>onChange({experience})}/>
      <p className={styles.note}>Based on an explicit experience requirement in the posting. This never changes your profile or application answers.</p>
      <ChoiceGroup label="Sponsorship signal" options={choices([["all","Any"],["likely","Likely sponsor"],["friendly","Include unknown"],["unlikely","Unlikely sponsor"]]).filter(o=>o.value==="all"||options.sponsorship?.includes(o.value)||o.value===value.sponsorship)} value={[value.sponsorship]} onChange={([sponsorship])=>onChange({sponsorship})}/>
      <fieldset className={styles.company}><legend>Companies · choose any</legend><input aria-label="Find a company" placeholder="Search companies…" value={companyQuery} onChange={event=>setCompanyQuery(event.target.value)}/><div>{options.companies.filter(c=>c.toLowerCase().includes(companyQuery.toLowerCase())).map(company=><label key={company}><input type="checkbox" checked={value.companies.includes(company)} onChange={()=>onChange({companies:value.companies.includes(company)?value.companies.filter(c=>c!==company):[...value.companies,company]})}/>{company}</label>)}</div></fieldset>
    </div></details>
    <div className={styles.bottom}><button type="button" onClick={()=>setOpen(false)}>Show {total.toLocaleString()} results</button><button type="button" onClick={onClear}>Clear all</button><button type="button" onClick={onFetch} disabled={scraping}>{scraping ? "Fetching…" : "Fetch new postings"}</button></div>
    <p className={styles.note}>Filters apply across the entire library. Multiple choices within a group match any selected option; different groups combine.</p>
  </div>;
  return <div className={styles.root}><div className={styles.active} aria-label="Active filters">{chips.map((chip,index)=><button key={`${chip.label}-${index}`} onClick={chip.remove} aria-label={`Remove filter: ${chip.label}`}>{chip.label} ×</button>)}{!chips.length&&<span>All roles · all locations</span>}{chips.length>0&&<button onClick={onClear}>Clear all</button>}</div>
    {mobile ? <><button className={styles.mobileTrigger} onClick={()=>setOpen(true)}>Filters · {chips.length} selected</button><SidePanelPortal open={open} onClose={()=>setOpen(false)} ariaLabelledBy="browse-filters-title" panelClassName={styles.mobilePanel}><div className={styles.mobileHead}><h2 id="browse-filters-title">Find your fit</h2><button onClick={()=>setOpen(false)} aria-label="Close filters">×</button></div>{controls}</SidePanelPortal></> : controls}
    <details className={styles.saved}><summary>Saved searches · {saved.length}</summary><div className={styles.savedList}>{saved.map(item=><div key={item.id}><button onClick={()=>onChange({...EMPTY_BROWSE,...item.filters})}>{item.name}</button><button aria-label={`Rename saved search ${item.name}`} onClick={()=>{setEditing(item.id);setRenameValue(item.name);}}>Rename</button>{editing===item.id&&<form onSubmit={e=>{e.preventDefault();void rename(item);}}><input aria-label="New search name" value={renameValue} maxLength={80} onChange={e=>setRenameValue(e.target.value)}/><button disabled={!renameValue.trim()}>Update name</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></form>}<button aria-label={`Delete saved search ${item.name}`} onClick={()=>void remove(item.id)}>×</button></div>)}</div><form onSubmit={event=>{event.preventDefault();void save();}}><input aria-label="Saved search name" placeholder="e.g. Seattle product roles" value={name} onChange={event=>setName(event.target.value)} maxLength={80} required/><button disabled={saving||!name.trim()}>{saving?"Saving…":"Save current filters"}</button></form>{error&&<p role="alert">{error}</p>}</details>
  </div>;
}
