#Requires -Version 5.1
<#
.SYNOPSIS
  First-time CareerOS setup: dependencies, Python venv, Playwright, Ollama, and Qwen model.

.EXAMPLE
  .\setup.bat
  .\scripts\setup.ps1 -Model qwen3:8b
  .\scripts\setup.ps1 -SkipOllama -SkipModels
#>
param(
    [string]$Model = "qwen3:8b",
    [switch]$SkipOllama,
    [switch]$SkipModels,
    [switch]$SkipExtension,
    [switch]$SkipTests
)

$ErrorActionPreference = "Stop"
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$ApiDir = Join-Path $RepoRoot "apps\api"
$WebDir = Join-Path $RepoRoot "apps\web"
$ExtDir = Join-Path $RepoRoot "apps\extension"
$VenvDir = Join-Path $ApiDir ".venv"
$VenvPython = Join-Path $VenvDir "Scripts\python.exe"
$ArsenalDir = Join-Path (Split-Path $RepoRoot -Parent) "Arsenal"

function Write-Step([string]$Message) {
    Write-Host ("==> " + $Message) -ForegroundColor Cyan
}

function Write-Ok([string]$Message) {
    Write-Host ("  OK  " + $Message) -ForegroundColor DarkGreen
}

function Write-Warn([string]$Message) {
    Write-Host ("  !!  " + $Message) -ForegroundColor Yellow
}

function Test-Command([string]$Name) {
    return [bool](Get-Command $Name -ErrorAction SilentlyContinue)
}

function Get-NodeMajorVersion {
    if (-not (Test-Command node)) { return 0 }
    $version = (node -v) -replace "^v", ""
    return [int]($version.Split(".")[0])
}

function Get-PythonLauncher {
    if (Test-Command python) {
        return @{ Exe = "python"; Args = @() }
    }
    if (Test-Command py) {
        return @{ Exe = "py"; Args = @("-3.11") }
    }
    return $null
}

function Invoke-PythonCommand {
    param([string[]]$CommandArgs)
    $launcher = Get-PythonLauncher
    if (-not $launcher) {
        throw "Python 3.11+ not found. Install from https://www.python.org/downloads/"
    }
    & $launcher.Exe @($launcher.Args + $CommandArgs)
}

function Ensure-Pnpm {
    if (Test-Command pnpm) {
        Write-Ok ("pnpm " + (pnpm -v))
        return
    }
    Write-Step "Enabling pnpm via Corepack"
    if (-not (Test-Command corepack)) {
        throw "pnpm not found and Corepack unavailable. Install Node 20+ then run: corepack enable"
    }
    corepack enable | Out-Null
    corepack prepare pnpm@9 --activate | Out-Null
    if (-not (Test-Command pnpm)) {
        throw "Failed to activate pnpm"
    }
    Write-Ok ("pnpm " + (pnpm -v))
}

function Copy-EnvIfMissing([string]$Source, [string]$Dest) {
    if (Test-Path $Dest) {
        Write-Ok ("Env exists: " + (Split-Path $Dest -Leaf))
        return
    }
    if (-not (Test-Path $Source)) {
        Write-Warn ("Template missing: " + $Source)
        return
    }
    Copy-Item $Source $Dest
    Write-Ok ("Created " + (Split-Path $Dest -Leaf) + " from template")
}

function Write-DefaultEnvFiles {
    Write-Step "Environment files"

    Copy-EnvIfMissing (Join-Path $RepoRoot ".env.example") (Join-Path $RepoRoot ".env")
    Copy-EnvIfMissing (Join-Path $ApiDir ".env.example") (Join-Path $ApiDir ".env")
    Copy-EnvIfMissing (Join-Path $ExtDir ".env.example") (Join-Path $ExtDir ".env")

    $webEnv = Join-Path $WebDir ".env.local"
    if (-not (Test-Path $webEnv)) {
        $extensionDist = (Join-Path $ExtDir "dist") -replace "\\", "/"
        @(
            "# Local overrides - generated by setup.ps1",
            "NEXT_PUBLIC_API_URL=http://localhost:8000",
            "NEXT_PUBLIC_EXTENSION_DIST_PATH=$extensionDist"
        ) | Set-Content -Path $webEnv -Encoding UTF8
        Write-Ok "Created apps/web/.env.local"
    } else {
        Write-Ok "Env exists: .env.local"
    }

    $envPath = Join-Path $RepoRoot ".env"
    if (Test-Path $envPath) {
        $content = Get-Content $envPath -Raw
        $replacements = @{
            "NEXT_PUBLIC_API_URL=http://localhost:8001" = "NEXT_PUBLIC_API_URL=http://localhost:8000"
            "CAREER_OS_API_PUBLIC_URL=http://localhost:8001" = "CAREER_OS_API_PUBLIC_URL=http://localhost:8000"
            "CAREER_OS_API_URL=http://localhost:8001" = "CAREER_OS_API_URL=http://localhost:8000"
            "APPLICATION_ASSISTANT_LLM_BASE_URL=http://localhost:1234/v1" = "APPLICATION_ASSISTANT_LLM_BASE_URL=http://localhost:11434/v1"
        }
        foreach ($pair in $replacements.GetEnumerator()) {
            $content = $content.Replace($pair.Key, $pair.Value)
        }
        if ($content -notmatch "APPLICATION_ASSISTANT_LLM_MODEL=") {
            $content += "`nAPPLICATION_ASSISTANT_LLM_MODEL=$Model`n"
        } elseif ($content -match "APPLICATION_ASSISTANT_LLM_MODEL=\s*$") {
            $content = $content -replace "APPLICATION_ASSISTANT_LLM_MODEL=\s*$", "APPLICATION_ASSISTANT_LLM_MODEL=$Model"
        }
        if ($content -notmatch "CHRONOS_MAPPING_ENABLED=") {
            $content += "`n# Application Assistant - local Ollama + field mapping`nCHRONOS_MAPPING_ENABLED=true`nCHRONOS_MAPPING_MODEL=$Model`nCHRONOS_MAPPING_CONFIDENCE=0.90`nCHRONOS_REVIEW_CONFIDENCE=0.70`n"
        }
        Set-Content -Path $envPath -Value $content.TrimEnd() -Encoding UTF8
        Write-Ok "Updated root .env with Ollama defaults"
    }
}

function Ensure-PythonVenv {
    Write-Step "Python virtual environment"
    $launcher = Get-PythonLauncher
    if (-not $launcher) {
        throw "Python 3.11+ not found. Install from https://www.python.org/downloads/"
    }

    $pyVersion = Invoke-PythonCommand @("-c", "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    Write-Ok ("Python " + ($pyVersion | Out-String).Trim())

    if (-not (Test-Path $VenvPython)) {
        Invoke-PythonCommand @("-m", "venv", $VenvDir)
        Write-Ok "Created apps/api/.venv"
    } else {
        Write-Ok "venv exists"
    }

    Write-Step "Installing Python dependencies"
    & $VenvPython -m pip install --upgrade pip | Out-Null
    & $VenvPython -m pip install -r (Join-Path $ApiDir "requirements.txt")
    Write-Ok "pip requirements installed"

    Write-Step "Installing Playwright Chromium"
    & $VenvPython -m playwright install chromium
    Write-Ok "Playwright Chromium ready"
}

function Test-OllamaRunning {
    try {
        $response = Invoke-WebRequest -Uri "http://127.0.0.1:11434/api/tags" -UseBasicParsing -TimeoutSec 4
        return $response.StatusCode -eq 200
    } catch {
        return $false
    }
}

function Ensure-Ollama {
    if ($SkipOllama) {
        Write-Warn "Skipping Ollama setup (-SkipOllama)"
        return
    }

    Write-Step "Ollama"
    if (-not (Test-Command ollama)) {
        Write-Host "  Ollama not found - installing via winget..."
        if (-not (Test-Command winget)) {
            throw "Install Ollama manually from https://ollama.com/download/windows then rerun setup"
        }
        winget install --id Ollama.Ollama -e --accept-source-agreements --accept-package-agreements
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
        if (-not (Test-Command ollama)) {
            throw "Ollama installed but not on PATH. Open a new terminal or reboot, then rerun setup"
        }
        Write-Ok "Ollama installed"
    } else {
        Write-Ok ("ollama " + (ollama --version 2>$null))
    }

    if (-not (Test-OllamaRunning)) {
        Write-Host "  Starting Ollama service..."
        Start-Process -FilePath "ollama" -ArgumentList "serve" -WindowStyle Hidden -ErrorAction SilentlyContinue | Out-Null
        $deadline = (Get-Date).AddSeconds(30)
        while ((Get-Date) -lt $deadline) {
            if (Test-OllamaRunning) { break }
            Start-Sleep -Seconds 2
        }
    }

    if (-not (Test-OllamaRunning)) {
        Write-Warn "Ollama is not responding on http://localhost:11434 - open the Ollama app, then run: ollama pull $Model"
        return
    }
    Write-Ok "Ollama API reachable"

    if ($SkipModels) {
        Write-Warn "Skipping model pull (-SkipModels)"
        return
    }

    Write-Step ("Pulling model '$Model' (this may take several minutes)")
    ollama pull $Model
    Write-Ok ("Model ready: " + $Model)
}

function Ensure-Arsenal {
    Write-Step "Arsenal workspace dependency"
    if (Test-Path $ArsenalDir) {
        Write-Ok ("Found " + $ArsenalDir)
        return
    }
    Write-Warn "Arsenal not found at $ArsenalDir"
    Write-Host "  CareerOS expects Arsenal as a sibling folder for shared packages."
    Write-Host "  Clone it next to CareerOS, then rerun: pnpm install"
    Write-Host "    cd $(Split-Path $RepoRoot -Parent)"
    Write-Host "    git clone YOUR-ARSENAL-REPO-URL Arsenal"
}

Write-Host ""
Write-Host "CareerOS first-time setup" -ForegroundColor Green
Write-Host ("Repo: " + $RepoRoot)
Write-Host ""

Write-Step "Checking prerequisites"
$nodeMajor = Get-NodeMajorVersion
if ($nodeMajor -lt 20) {
    throw "Node.js 20+ required (found v$nodeMajor). Install from https://nodejs.org/"
}
Write-Ok ("Node " + (node -v))

Ensure-Pnpm
Ensure-Arsenal
Write-DefaultEnvFiles

Write-Step "Installing JavaScript dependencies"
Set-Location $RepoRoot
pnpm install
Write-Ok "pnpm install complete"

Ensure-PythonVenv
Ensure-Ollama

if (-not $SkipExtension) {
    Write-Step "Building Chrome extension"
    pnpm --filter @career-os/extension build
    Write-Ok "Extension built to apps/extension/dist"
}

if (-not $SkipTests) {
    Write-Step "Running API smoke tests"
    & $VenvPython -m pytest (Join-Path $ApiDir "tests\test_field_answers.py") (Join-Path $ApiDir "tests\test_semantic_field_resolution.py") -q
    Write-Ok "API smoke tests passed"
}

Write-Step "Installing git hooks (pre-commit + pre-push run pnpm ci)"
& (Join-Path $PSScriptRoot "install-git-hooks.ps1")

Write-Host ""
Write-Host "Setup complete" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Start dev servers:  .\restart-dev.bat -Background"
Write-Host "     or foreground:       pnpm dev"
Write-Host "  2. Open dashboard:     http://localhost:3000/application-assistant"
Write-Host "  3. API docs:           http://localhost:8000/docs"
Write-Host "  4. Load extension:     chrome://extensions -> Load unpacked -> apps/extension/dist"
Write-Host ""
Write-Host ("LLM: http://localhost:11434/v1  model: " + $Model)
Write-Host ""
