#!/usr/bin/env bash
# First-time CareerOS setup: dependencies, Python venv, Playwright, Ollama, and Qwen model.
set -euo pipefail

MODEL="qwen3:8b"
SKIP_OLLAMA=0
SKIP_MODELS=0
SKIP_EXTENSION=0
SKIP_TESTS=0

usage() {
  cat <<EOF
Usage: ./scripts/setup.sh [options]

Options:
  --model NAME         Ollama model to pull (default: qwen3:8b)
  --skip-ollama        Skip Ollama install/start
  --skip-models        Skip ollama pull
  --skip-extension     Skip extension build
  --skip-tests         Skip API smoke tests
  -h, --help           Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --model) MODEL="$2"; shift 2 ;;
    --skip-ollama) SKIP_OLLAMA=1; shift ;;
    --skip-models) SKIP_MODELS=1; shift ;;
    --skip-extension) SKIP_EXTENSION=1; shift ;;
    --skip-tests) SKIP_TESTS=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown option: $1"; usage; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$REPO_ROOT/apps/api"
WEB_DIR="$REPO_ROOT/apps/web"
EXT_DIR="$REPO_ROOT/apps/extension"
VENV_DIR="$API_DIR/.venv"
ARSENAL_DIR="$(cd "$REPO_ROOT/.." && pwd)/Arsenal"

step() { printf '\033[36m==> %s\033[0m\n' "$1"; }
ok() { printf '\033[32m  OK  %s\033[0m\n' "$1"; }
warn() { printf '\033[33m  !!  %s\033[0m\n' "$1"; }

command_exists() { command -v "$1" >/dev/null 2>&1; }

ollama_running() {
  curl -fsS --max-time 4 http://127.0.0.1:11434/api/tags >/dev/null 2>&1
}

ensure_pnpm() {
  if command_exists pnpm; then
    ok "pnpm $(pnpm -v)"
    return
  fi
  step "Enabling pnpm via Corepack"
  command_exists corepack || { echo "Install Node 20+ with Corepack, or install pnpm globally."; exit 1; }
  corepack enable
  corepack prepare pnpm@9 --activate
  ok "pnpm $(pnpm -v)"
}

copy_env_if_missing() {
  local src="$1" dest="$2"
  if [[ -f "$dest" ]]; then
    ok "Env exists: $(basename "$dest")"
    return
  fi
  if [[ ! -f "$src" ]]; then
    warn "Template missing: $src"
    return
  fi
  cp "$src" "$dest"
  ok "Created $(basename "$dest") from template"
}

write_default_env_files() {
  step "Environment files"
  copy_env_if_missing "$REPO_ROOT/.env.example" "$REPO_ROOT/.env"
  copy_env_if_missing "$API_DIR/.env.example" "$API_DIR/.env"
  copy_env_if_missing "$EXT_DIR/.env.example" "$EXT_DIR/.env"

  if [[ ! -f "$WEB_DIR/.env.local" ]]; then
    cat >"$WEB_DIR/.env.local" <<EOF
# Local overrides — generated by setup.sh
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_EXTENSION_DIST_PATH=$EXT_DIR/dist
EOF
    ok "Created apps/web/.env.local"
  else
    ok "Env exists: .env.local"
  fi

  if [[ -f "$REPO_ROOT/.env" ]]; then
    sed -i.bak \
      -e 's|http://localhost:8001|http://localhost:8000|g' \
      -e 's|http://localhost:1234/v1|http://localhost:11434/v1|g' \
      "$REPO_ROOT/.env" || true
    rm -f "$REPO_ROOT/.env.bak"
    if ! grep -q '^APPLICATION_ASSISTANT_LLM_MODEL=' "$REPO_ROOT/.env"; then
      printf '\nAPPLICATION_ASSISTANT_LLM_MODEL=%s\n' "$MODEL" >>"$REPO_ROOT/.env"
    fi
    if ! grep -q '^CHRONOS_MAPPING_ENABLED=' "$REPO_ROOT/.env"; then
      cat >>"$REPO_ROOT/.env" <<EOF

# Application Assistant — local Ollama + field mapping
CHRONOS_MAPPING_ENABLED=true
CHRONOS_MAPPING_MODEL=$MODEL
CHRONOS_MAPPING_CONFIDENCE=0.90
CHRONOS_REVIEW_CONFIDENCE=0.70
EOF
    fi
    ok "Updated root .env with Ollama defaults"
  fi
}

ensure_python_venv() {
  step "Python virtual environment"
  PYTHON=""
  for candidate in python3.11 python3 python; do
    if command_exists "$candidate"; then
      PYTHON="$candidate"
      break
    fi
  done
  [[ -n "$PYTHON" ]] || { echo "Python 3.11+ required."; exit 1; }
  ok "$("$PYTHON" --version)"

  if [[ ! -d "$VENV_DIR" ]]; then
    "$PYTHON" -m venv "$VENV_DIR"
    ok "Created apps/api/.venv"
  else
    ok "venv exists"
  fi

  step "Installing Python dependencies"
  "$VENV_DIR/bin/python" -m pip install --upgrade pip >/dev/null
  "$VENV_DIR/bin/python" -m pip install -r "$API_DIR/requirements.txt"
  ok "pip requirements installed"

  step "Installing Playwright Chromium"
  "$VENV_DIR/bin/python" -m playwright install chromium
  ok "Playwright Chromium ready"
}

ensure_ollama() {
  if [[ "$SKIP_OLLAMA" -eq 1 ]]; then
    warn "Skipping Ollama setup (--skip-ollama)"
    return
  fi

  step "Ollama"
  if ! command_exists ollama; then
    echo "  Installing Ollama..."
    if command_exists brew; then
      brew install ollama
    else
      curl -fsSL https://ollama.com/install.sh | sh
    fi
  fi
  ok "ollama $(ollama --version 2>/dev/null || echo installed)"

  if ! ollama_running; then
    echo "  Starting Ollama..."
    (ollama serve >/dev/null 2>&1 &) || true
    for _ in $(seq 1 15); do
      ollama_running && break
      sleep 2
    done
  fi

  if ! ollama_running; then
    warn "Ollama not responding — start it manually, then: ollama pull $MODEL"
    return
  fi
  ok "Ollama API reachable"

  if [[ "$SKIP_MODELS" -eq 1 ]]; then
    warn "Skipping model pull (--skip-models)"
    return
  fi

  step "Pulling model '$MODEL' (this may take several minutes)"
  ollama pull "$MODEL"
  ok "Model ready: $MODEL"
}

ensure_arsenal() {
  step "Arsenal workspace dependency"
  if [[ -d "$ARSENAL_DIR" ]]; then
    ok "Found $ARSENAL_DIR"
    return
  fi
  warn "Arsenal not found at $ARSENAL_DIR"
  echo "  Clone it as a sibling folder, then rerun: pnpm install"
  echo "    cd $(dirname "$REPO_ROOT")"
  echo "    git clone YOUR-ARSENAL-REPO-URL Arsenal"
}

printf '\n\033[32mCareerOS first-time setup\033[0m\n'
echo "Repo: $REPO_ROOT"
echo ""

step "Checking prerequisites"
command_exists node || { echo "Node.js 20+ required."; exit 1; }
NODE_MAJOR="$(node -v | sed 's/^v//' | cut -d. -f1)"
[[ "$NODE_MAJOR" -ge 20 ]] || { echo "Node.js 20+ required (found $(node -v))."; exit 1; }
ok "Node $(node -v)"

ensure_pnpm
ensure_arsenal
write_default_env_files

step "Installing JavaScript dependencies"
(cd "$REPO_ROOT" && pnpm install)
ok "pnpm install complete"

ensure_python_venv
ensure_ollama

if [[ "$SKIP_EXTENSION" -eq 0 ]]; then
  step "Building Chrome extension"
  (cd "$REPO_ROOT" && pnpm --filter @career-os/extension build)
  ok "Extension built to apps/extension/dist"
fi

if [[ "$SKIP_TESTS" -eq 0 ]]; then
  step "Running API smoke tests"
  "$VENV_DIR/bin/python" -m pytest \
    "$API_DIR/tests/test_field_answers.py" \
    "$API_DIR/tests/test_semantic_field_resolution.py" -q
  ok "API smoke tests passed"
fi

step "Installing git hooks (pre-commit + pre-push run pnpm ci)"
bash "$REPO_ROOT/scripts/install-git-hooks.sh"

cat <<EOF

Setup complete

Next steps:
  1. Start dev servers:  pnpm dev
     macOS/Linux:       ./scripts/restart-dev.sh -Background  (if added) or pnpm dev
  2. Open dashboard:     http://localhost:3000/application-assistant
  3. API docs:           http://localhost:8000/docs
  4. Load extension:     chrome://extensions -> Load unpacked -> apps/extension/dist

LLM: http://localhost:11434/v1  model: $MODEL

EOF
