import type { CorpusProfile, CorpusRecord } from "./corpus-model";
import { INITIAL_CORPUS_RECORDS } from "./corpus-seed-data";
import { emptyPhaseOneData } from "./phase1-model";

const questionLinks = {
  evidenceIds: [] as string[],
  metricIds: [] as string[],
  followUpQuestions: [] as string[],
  reviewerFeedback: [] as string[],
  practiceHistory: [] as string[],
};

const corpusRecordDefaults = {
  alternatives: "",
  crossTeamInfluence: "",
  mentorship: "",
  missingItemMetadata: {},
  qualityStatusOverrides: {},
  phaseOne: emptyPhaseOneData(),
} satisfies Pick<
  CorpusRecord,
  "alternatives" | "crossTeamInfluence" | "mentorship" | "missingItemMetadata" | "qualityStatusOverrides" | "phaseOne"
>;

export const PREVIEW_PROFILE: CorpusProfile = {
  fullName: "Alex Morgan",
  currentTitle: "Staff Platform Engineer",
  targetRole: "Staff / Principal Platform Engineer",
  yearsExperience: "11 years",
  primaryDomains: ["Distributed systems", "Developer platforms", "AI infrastructure"],
};

const SHOWCASE_PREVIEW_RECORDS: CorpusRecord[] = [
  {
    ...corpusRecordDefaults,
    id: "preview-routing",
    title: "Regional event-routing platform",
    company: "Northstar Cloud",
    role: "Staff Platform Engineer",
    project: "Event fabric",
    timePeriod: "2024 — 2026",
    summary: "Regional teams operated separate ingestion paths with inconsistent failover behavior and no shared ownership model.",
    currentBullet: "Led a multi-region event platform that unified 14 ingestion services, raised availability to 99.99%, and cut recovery time by 62% across 11 regions.",
    technicalChallenge: "Preserve regional ordering and tenant isolation while providing predictable failover across uneven traffic profiles.",
    architectureDecision: "Adopted regional partition ownership with an asynchronous reconciliation stream instead of global consensus on the hot path.",
    tradeoffs: "Accepted bounded cross-region staleness to keep regional writes available and failure domains isolated.",
    failureModes: "Replay storms, partition rebalancing, and cross-region dependency loss were tested through staged fault injection.",
    reliabilityAndScale: "Regional failover, replay protection, and capacity isolation across 11 regions.",
    reliabilityDetails: "Defined regional SLOs, bounded replay queues, and automated isolation when downstream consumers fell behind.",
    securityConsiderations: "Kept tenant routing keys isolated and restricted cross-region replication to approved residency boundaries.",
    scaleDetails: "14 ingestion services · 11 regions · uneven tenant traffic with burst isolation.",
    businessImpact: "Removed regional launch blockers and gave product teams one supported ingestion contract.",
    engineeringImpact: "Reduced recovery time by 62% and replaced 14 divergent ingestion paths with one operated platform.",
    leadership: "Technical lead and architecture owner across three platform teams; facilitated design reviews and rollout standards.",
    technologies: ["Kubernetes", "Kafka", "Go", "OpenTelemetry"],
    domains: ["Distributed systems", "Platform engineering"],
    concepts: ["Partition ownership", "Backpressure", "Regional isolation", "Fault injection"],
    ownership: "Owned architecture, cross-team migration sequencing, failure testing, and production readiness.",
    readiness: "ready",
    completeness: 92,
    roastResistance: 91,
    impactScore: 94,
    evidenceScore: 88,
    architectureCovered: true,
    leadershipCovered: true,
    metrics: [
      { id: "routing-availability", name: "Availability", value: "99.99%", unit: "%", source: "Reliability scorecard", confidence: "high", verification: "verified", evidenceIds: [] },
      { id: "routing-recovery", name: "Recovery time", value: "−62%", unit: "%", source: "Incident analytics", confidence: "high", verification: "verified", evidenceIds: [] },
      { id: "routing-regions", name: "Regional scope", value: "11 regions", unit: "regions", source: "Launch plan", confidence: "high", verification: "verified", evidenceIds: [] },
    ],
    evidence: [
      { id: "routing-rfc", name: "Kafka event fabric architecture RFC", type: "rfc", url: "#routing-rfc", relatedGapIds: [] },
      { id: "routing-scorecard", name: "OpenTelemetry reliability scorecard", type: "dashboard", url: "#routing-scorecard", relatedGapIds: [] },
    ],
    concerns: [
      { id: "routing-concern", reviewer: "Staff engineer", category: "Tradeoffs", severity: "medium", concern: "Explain the cost and operability tradeoff behind active-active regional replication.", status: "answered" },
    ],
    interviewQuestions: [
      { id: "routing-q1", question: "How did you choose partitioning and ordering guarantees across regions?", interviewType: "System design", reviewerPersona: "Principal engineer", difficulty: "expert", answerStatus: "prepared", preparedAnswer: "I separated regional write ownership from asynchronous reconciliation so ordering stayed local and failover remained bounded.", confidence: 86, ...questionLinks },
      { id: "routing-q2", question: "What failed during the rollout, and what did you change?", interviewType: "Technical deep dive", reviewerPersona: "Staff engineer", difficulty: "advanced", answerStatus: "practiced", preparedAnswer: "A replay storm exposed an unbounded recovery queue; we added admission control, per-tenant budgets, and staged fault injection.", confidence: 82, ...questionLinks },
    ],
    resumeVariants: [
      { id: "routing-current", name: "Platform leadership", content: "Led a multi-region event platform that unified 14 ingestion services, raised availability to 99.99%, and cut recovery time by 62% across 11 regions.", status: "published" },
      { id: "routing-concise", name: "Concise", content: "Unified 14 ingestion services on a multi-region platform, achieving 99.99% availability and 62% faster recovery.", status: "draft" },
    ],
    linkedInVersion: "Led the architecture and rollout of a regional event fabric used across 11 regions, balancing availability, data residency, and operability.",
    portfolioVersion: "A technical case study covering partition ownership, bounded staleness, replay protection, and regional failure isolation.",
    missingInformation: ["Business impact beyond launch enablement"],
    nextImprovement: "Practice the cost-model follow-up with a two-minute whiteboard explanation.",
    updatedAt: "2026-07-14T18:40:00.000Z",
  },
  {
    ...corpusRecordDefaults,
    id: "preview-evaluation",
    title: "Model evaluation control plane",
    company: "Atlas Labs",
    role: "Staff Software Engineer",
    project: "Evaluation infrastructure",
    timePeriod: "2022 — 2024",
    summary: "Model teams ran bespoke evaluation jobs with duplicate GPU spend, inconsistent policy checks, and limited queue fairness.",
    currentBullet: "Built a policy-driven evaluation control plane that increased experiment throughput 4.1× and reduced duplicate GPU spend by 34% for 70+ model teams.",
    technicalChallenge: "Schedule heterogeneous workloads fairly while enforcing reproducibility, cost, and safety policy at submission time.",
    architectureDecision: "Separated a deterministic policy and scheduling control plane from elastic execution workers.",
    tradeoffs: "Chose predictable policy evaluation and observable queues over direct team ownership of raw clusters.",
    failureModes: "Addressed poisoned work queues, worker loss, runaway retries, and high-volume team starvation.",
    reliabilityAndScale: "70+ model teams across shared GPU pools.",
    reliabilityDetails: "Used idempotent leases, retry budgets, and queue health alerts.",
    securityConsiderations: "Policy evaluation blocked unapproved datasets and execution environments before work entered the queue.",
    scaleDetails: "70+ teams · shared GPU pools · bursty evaluation workloads.",
    businessImpact: "Lowered duplicate compute spending and shortened model-release feedback loops.",
    engineeringImpact: "Increased experiment throughput 4.1× with one observable scheduling and policy surface.",
    leadership: "Aligned model, infrastructure, and finance stakeholders on allocation policy and migration sequencing.",
    technologies: ["Python", "Ray", "Kubernetes", "PostgreSQL"],
    domains: ["AI infrastructure", "Platform engineering"],
    concepts: ["Control planes", "Fair scheduling", "Idempotency", "Policy enforcement"],
    ownership: "Owned the control-plane architecture and core scheduler; partner teams owned worker adapters.",
    readiness: "review",
    completeness: 84,
    roastResistance: 78,
    impactScore: 88,
    evidenceScore: 64,
    architectureCovered: true,
    leadershipCovered: true,
    metrics: [
      { id: "eval-throughput", name: "Experiment throughput", value: "4.1×", unit: "multiplier", source: "Capacity review", confidence: "high", verification: "verified", evidenceIds: [] },
      { id: "eval-cost", name: "Duplicate GPU spend", value: "−34%", unit: "%", source: "FinOps estimate", confidence: "medium", verification: "needs-evidence", evidenceIds: [] },
    ],
    evidence: [{ id: "eval-rfc", name: "Kubernetes evaluation control-plane RFC", type: "rfc", url: "#evaluation-rfc", relatedGapIds: [] }],
    concerns: [
      { id: "eval-concern", reviewer: "Principal engineer", category: "Ownership", severity: "high", concern: "Clarify which fairness and retry mechanisms you personally designed.", status: "investigating" },
    ],
    interviewQuestions: [
      { id: "eval-q1", question: "How did the scheduler prevent high-volume teams from starving smaller workloads?", interviewType: "AI infrastructure", reviewerPersona: "AI infrastructure reviewer", difficulty: "expert", answerStatus: "unanswered", confidence: 35, ...questionLinks },
      { id: "eval-q2", question: "Why build a control plane instead of standardizing on an existing evaluation product?", interviewType: "System design", reviewerPersona: "Principal engineer", difficulty: "expert", answerStatus: "draft", preparedAnswer: "Existing products did not enforce our dataset and cost policy at submission time; the answer still needs a quantified comparison.", confidence: 58, ...questionLinks },
    ],
    resumeVariants: [{ id: "eval-current", name: "AI infrastructure", content: "Built a policy-driven evaluation control plane that increased experiment throughput 4.1× and reduced duplicate GPU spend by 34% for 70+ model teams.", status: "draft" }],
    linkedInVersion: "Built shared evaluation infrastructure that made model experimentation faster, more governable, and easier to operate.",
    portfolioVersion: "Control-plane architecture for policy-aware, fair scheduling across shared accelerator pools.",
    missingInformation: ["Fairness mechanism detail", "Validate the 34% cost estimate"],
    nextImprovement: "Attach the cost-analysis source and prepare the queue-fairness explanation.",
    updatedAt: "2026-07-12T16:15:00.000Z",
  },
  {
    ...corpusRecordDefaults,
    id: "preview-delivery",
    title: "Progressive delivery safety program",
    company: "Meridian Systems",
    role: "Senior Platform Engineer",
    project: "Delivery reliability",
    timePeriod: "2020 — 2022",
    summary: "Service teams shipped through inconsistent deployment paths with limited rollback signals and recurring production regressions.",
    currentBullet: "Established progressive-delivery standards across 120 services, reducing change-failure rate from 8.4% to 3.1% while shortening median lead time by 46%.",
    technicalChallenge: "Standardize safe rollout signals without blocking teams with different traffic patterns and risk profiles.",
    architectureDecision: "Created a common rollout contract with service-owned thresholds and platform-enforced promotion gates.",
    tradeoffs: "Allowed teams to tune thresholds while standardizing the minimum telemetry and rollback contract.",
    failureModes: "Handled noisy metrics, low-traffic services, alert lag, and rollback dependency failures.",
    reliabilityAndScale: "120 services with heterogeneous release patterns.",
    reliabilityDetails: "Promotion gates combined error-budget burn, latency, and service-specific health checks.",
    securityConsiderations: "Deployment policy changes required review and produced an auditable trail.",
    scaleDetails: "120 services · multiple release cadences · shared promotion controller.",
    businessImpact: "Reduced customer-visible regressions and made release timing more predictable.",
    engineeringImpact: "Cut change-failure rate from 8.4% to 3.1% and median lead time by 46%.",
    leadership: "Authored standards, ran migrations with eight product groups, and coached service owners on rollout design.",
    technologies: ["TypeScript", "Argo Rollouts", "Prometheus", "Kubernetes"],
    domains: ["Developer platforms", "Reliability"],
    concepts: ["Progressive delivery", "Error budgets", "Automated rollback"],
    ownership: "Owned the standard, reference controller, adoption program, and reliability review cadence.",
    readiness: "ready",
    completeness: 90,
    roastResistance: 87,
    impactScore: 91,
    evidenceScore: 92,
    architectureCovered: true,
    leadershipCovered: true,
    metrics: [
      { id: "delivery-cfr", name: "Change-failure rate", value: "8.4% → 3.1%", unit: "%", source: "Quarterly reliability review", confidence: "high", verification: "verified", evidenceIds: [] },
      { id: "delivery-lead", name: "Median lead time", value: "−46%", unit: "%", source: "Delivery analytics", confidence: "high", verification: "verified", evidenceIds: [] },
      { id: "delivery-services", name: "Service adoption", value: "120 services", unit: "services", source: "Platform inventory", confidence: "high", verification: "verified", evidenceIds: [] },
    ],
    evidence: [
      { id: "delivery-standard", name: "Argo Rollouts progressive delivery standard", type: "document", url: "#delivery-standard", relatedGapIds: [] },
      { id: "delivery-dashboard", name: "Prometheus change safety dashboard", type: "dashboard", url: "#delivery-dashboard", relatedGapIds: [] },
      { id: "delivery-review", name: "Quarterly reliability review", type: "review", url: "#delivery-review", relatedGapIds: [] },
    ],
    concerns: [],
    interviewQuestions: [
      { id: "delivery-q1", question: "How did you win adoption without making the platform a release bottleneck?", interviewType: "Staff-level probing", reviewerPersona: "Staff engineer", difficulty: "advanced", answerStatus: "prepared", preparedAnswer: "We standardized the safety contract while letting teams own thresholds, then proved value with early adopters before enforcing a minimum baseline.", confidence: 84, ...questionLinks },
    ],
    resumeVariants: [{ id: "delivery-current", name: "Platform leadership", content: "Established progressive-delivery standards across 120 services, reducing change-failure rate from 8.4% to 3.1% while shortening median lead time by 46%.", status: "published" }],
    linkedInVersion: "Led a progressive-delivery program spanning 120 services and eight product groups.",
    portfolioVersion: "How a shared rollout contract reduced change failures without centralizing every release decision.",
    missingInformation: [],
    nextImprovement: "Add one concrete example of a team-specific threshold and the adoption objection it resolved.",
    updatedAt: "2026-07-10T20:05:00.000Z",
  },
  {
    ...corpusRecordDefaults,
    id: "preview-identity",
    title: "Customer identity migration",
    company: "Juniper Digital",
    role: "Senior Software Engineer",
    project: "Unified identity",
    timePeriod: "2018 — 2020",
    summary: "Three products maintained duplicate identity workflows, inconsistent audit data, and brittle account linking.",
    currentBullet: "Designed the migration path for a unified customer identity service across three products, eliminating duplicate account workflows and improving audit consistency.",
    technicalChallenge: "Migrate identities without account loss, authorization drift, or extended dual-write inconsistency.",
    architectureDecision: "Used staged account linking and compatibility adapters before transferring source-of-truth ownership.",
    tradeoffs: "Accepted a longer dual-read window to make reconciliation observable and reversible.",
    failureModes: "Document partial migration, duplicate-link, and rollback behavior before claiming production depth.",
    reliabilityAndScale: "Scale and migration reliability need supporting detail.",
    reliabilityDetails: "",
    securityConsiderations: "Authorization and audit requirements need explicit documentation.",
    scaleDetails: "Three products; user and account volume still needs validation.",
    businessImpact: "Reduced duplicate customer-account workflows; the quantified customer outcome is still missing.",
    engineeringImpact: "Improved audit consistency across three products.",
    leadership: "Coordinated migration sequencing with three product teams.",
    technologies: ["Java", "PostgreSQL", "OAuth 2.0"],
    domains: ["Security", "Identity"],
    concepts: ["Identity migration", "Dual reads", "Reconciliation"],
    ownership: "Designed the migration path; implementation ownership by phase still needs clarification.",
    readiness: "needs-input",
    completeness: 67,
    roastResistance: 65,
    impactScore: 61,
    evidenceScore: 15,
    architectureCovered: true,
    leadershipCovered: true,
    metrics: [],
    evidence: [],
    concerns: [
      { id: "identity-concern", reviewer: "Security reviewer", category: "Evidence", severity: "high", concern: "The migration and audit claims need a safe source and explicit authorization controls.", status: "unanswered" },
    ],
    interviewQuestions: [
      { id: "identity-q1", question: "How did you prevent authorization drift during dual reads?", interviewType: "Security", reviewerPersona: "Security reviewer", difficulty: "advanced", answerStatus: "unanswered", confidence: 22, ...questionLinks },
    ],
    resumeVariants: [{ id: "identity-current", name: "Current", content: "Designed the migration path for a unified customer identity service across three products, eliminating duplicate account workflows and improving audit consistency.", status: "draft" }],
    linkedInVersion: "",
    portfolioVersion: "",
    missingInformation: ["Customer or account volume", "Authorization controls", "Migration evidence", "Quantified business impact"],
    nextImprovement: "Validate user scale and attach a safe migration or audit artifact before using this bullet.",
    updatedAt: "2026-07-06T14:30:00.000Z",
  },
];

const SHOWCASE_RECORD_IDS = new Set(SHOWCASE_PREVIEW_RECORDS.map((record) => record.id));

export const PREVIEW_RECORDS: CorpusRecord[] = [
  ...SHOWCASE_PREVIEW_RECORDS,
  ...INITIAL_CORPUS_RECORDS.filter((record) => !SHOWCASE_RECORD_IDS.has(record.id)),
];
